python3-catkin-pkg:
  opensuse: [python3-catkin-pkg]
python3-catkin-pkg-modules:
  opensuse: [python3-catkin-pkg]
liborocos-kdl-dev:
  opensuse: [orocos-kdl-devel]
liborocos-kdl:
  opensuse: [liborocos-kdl]
spdlog:
  opensuse: [spdlog-devel]
lm-sensors:
  opensuse: [sensors]
python3-rosdep-modules:
  opensuse: [python3-rosdep]
python3-pykdl:
  opensuse: [python3-pykdl]
apr:
  opensuse: [libapr1-0, libapr-util1-0]
boost:
  opensuse: [libboost_atomic-devel, libboost_headers-devel, libboost_system-devel, libboost_thread-devel, libboost_chrono-devel, libboost_date_time-devel, libboost_serialization-devel, libboost_filesystem-devel, libboost_program_options-devel, libboost_python3-devel, libboost_regex-devel, libboost_iostreams-devel]
libboost-chrono-dev:
  opensuse: [libboost_chrono-devel]
libboost-date-time-dev:
  opensuse: [libboost_date_time-devel]
libboost-regex-dev:
  opensuse: [libboost_regex-devel]
libboost-system-dev:
  opensuse: [libboost_system-devel]
libboost-thread-dev:
  opensuse: [libboost_thread-devel]
libboost-program-options-dev:
  opensuse: [libboost_program_options-devel]
libboost-dev:
  opensuse: [libboost_headers-devel]
libboost-headers-dev:
  opensuse: [libboost_headers-devel]
libboost-filesystem-dev:
  opensuse: [libboost_filesystem-devel]
libboost-thread:
  opensuse: [libboost_thread1_85_0]
libconsole-bridge-dev:
  opensuse: [libconsole_bridge-devel]
yapf:
  opensuse: [python3-yapf]
python3-importlib-metadata:
  opensuse: [python3-importlib-metadata]
libatomic:
  opensuse: [libatomic1]
pybind11-dev:
  opensuse: [python3-pybind11-devel]
yaml:
  opensuse: [libyaml-devel]
python3-importlib-resources:
  opensuse: [python3-importlib-resources]
python3-vcstool:
  opensuse: [python3-vcstool]
libxml2-utils:
  opensuse: [libxml2-tools]
libsqlite3-dev:
  opensuse: [sqlite3-devel]
benchmark:
  opensuse: [benchmark-devel]
libzstd-dev:
  opensuse: [libzstd-devel]
python3-argcomplete:
  opensuse: [python3-argcomplete]
python3-rosdistro-modules:
  opensuse: [python3-rosdistro]
python3-lark-parser:
  opensuse: [python3-lark-parser]
file:
  opensuse: [file]
clang-tidy:
  opensuse: [clang-tools]
cppcheck:
  opensuse: [cppcheck]
python3-pytest-cov:
  opensuse: [python3-pytest-cov]
python3-packaging:
  opensuse: [python3-packaging]
python3-fastjsonschema:
  opensuse: [python3-fastjsonschema]
clang-format:
  opensuse: [clang-tools]
liblttng-ust-dev:
  opensuse: [lttng-ust-devel]
uncrustify:
  opensuse: [uncrustify]
lttng-tools:
  opensuse: [lttng-tools]
pydocstyle:
  opensuse: [python3-pydocstyle]
libxrandr:
  opensuse: [libXrandr-devel]
pyflakes3:
  opensuse: [python3-pyflakes]
python3-flake8-comprehensions:
  opensuse: [python3-flake8-comprehensions]
libfreetype6:
  opensuse: [libfreetype6]
python3-jsonschema:
  opensuse: [python3-jsonschema]
asio:
  opensuse: [asio-devel]
libncurses-dev:
  opensuse: [ncurses-devel]
acl:
  opensuse: [acl, libacl-devel]
liblz4:
  opensuse: [liblz4-devel]
libqt5-svg:
  opensuse: [libqt5-qtsvg-devel]
libxxf86vm:
  opensuse: [libXxf86vm-devel]
libxaw:
  opensuse: [libXaw-devel]
libudev-dev:
  opensuse: [systemd-devel]
